version: '3'
services:
  submissions-api:
    image: submissions-api:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - api.env
    ports:
      - 3000:3000
    command: npm start
    network_mode: "host"
